### ISSUE TITLE
Lab 2 

### ISSUE THREAD

**Issue by asukajames** [Watts-College/cpp-526-spr-2022#1]
Hello, I am confused with # Assign test (logical) output to object 'result' by replacing 'FALSE'". 
If we result <- FALSE, doesn't our map coloring code be affected? or I am doing wrong because I see just a gray map!

**Comment by gmcirco** [comment]
For this assignment you need to replace the value `FALSE` with another value. If you leave it as-is, you will not select any values at all - and will get a blank gray map.

For example, doing the following will give you all commercial properties:

`result <- downtown$landuse == "Commercial"`

You will see that `result` stores a vector of `TRUE` and `FALSE` values that are passed to the next function.

**Comment by asukajames** [comment]
@gmcirco 
Dr. Circo, thank you for your response! 
I was able to create the map of parking lots in downtown Syracuse using these functions but I think I am still confused: 
```{r}
result <- downtown$landuse == "Parking"
sum(result, na.rm = TRUE)

group.colors <- ifelse(test = result, 
                       yes = "firebrick", 
                       no = "gray80")

plot(downtown,
     border = NA, 
     col = group.colors)
```
and I need to replace result by False and create another map? 
```{r}
result <- FALSE
group.colors <- ifelse(test = result, 
                       yes = "firebrick", 
                       no = "gray80")

plot(downtown,
     border = NA, 
     col = group.colors)
```

**Comment by gmcirco** [comment]
You will need to replace the `FALSE` for each code block. Essentially you are resetting it for each question and re-running it. When you knit the document all the proper maps will be rendered.

**Comment by asukajames** [comment]
Thank you @gmcirco !

**Comment by CarlyDeal** [comment]
I'm confused on when we put:
result <- FALSE

Is it before result 
<- downtown$landuse == "Parking"
sum(result, na.rm = TRUE)

or before:
group.colors <- ifelse(test = result, 
                       yes = "firebrick", 
                       no = "gray80")

plot(downtown,
     border = NA, 
     col = group.colors)

**Comment by gmcirco** [comment]
You are assigning TRUE/FALSE values to the variable `reply`. So everything has to come AFTER. In your example:

`result <- downtown$landuse == "Parking"`

**Comment by CarlyDeal** [comment]
Thank you! I got it to work!
