### ISSUE TITLE
Lab 3:

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#10]
I'm stuck on getting the blue line on the graph. In another students post you mentioned creating a line chart.

To create the line chart do we use:
line()

Do we have to define average per-year? I'm a little confused on code for creating the blue line.

**Comment by asukajames** [comment]
@CarlyDeal 
It is already prepared at the beginning of this dataset.
```{r}
league.ave <- tapply(X = ave.so, 
                     INDEX = as.factor(year), 
                     FUN = "mean", 
                     na.rm = TRUE)                # Calculating league strikeout average/season

league.year <- as.numeric(names(league.ave))      # Ensuring years are numeric, not text
```
You can use these in the line function and you need to add points as well:-) 
(that's how I approached!)

**Comment by CarlyDeal** [comment]
@asukajames what exactly does your code look like? 

points(x = year, 
        y = league.ave,
        col = "steelblue4",              
        pch = 16,                    
        cex = 0.75)

but I  get an error saying: Error in xy.coords(x, y) : 'x' and 'y' lengths differ

I  then tried:

ave.league.min <- min(league.ave, na.rm=TRUE)
ave.league.max <- max(league.ave, na.rm=TRUE)

plot.window(xlim = c(1900, 2012),
             ylim = c(ave.league.min,
                      ave.league.max))
points(x=year,
           y=league.ave)

and got " Error in xy.coords(x, y) : 'x' and 'y' lengths differ".

Not sure if either of these are remotely close to what needs to be done.

**Comment by gmcirco** [comment]
@CarlyDeal 

The code to create the year over year average can be done using the two provided variables calculated at the top of the document. They are:

`league.year` and `league.ave`

You'll notice they have the same length - 150.

`length(league.year)`
`length(league.ave)`

You are trying to use the variable `year` which is different. This corresponds to an individual year for each team-year combination. You'll notice that the length is much longer: 2955

`length(year)`

For your plot, you should be doing something akin to this:

`lines(x = league.year, y = league.ave, lwd = 2, col = "darkblue")`
