### ISSUE TITLE
Installing R studio on the employer's PC

### ISSUE THREAD

**Issue by ilhemsaadaoui** [Watts-College/cpp-526-spr-2022#11]
For the previous labs, I installed R studio on my pc to solve them. Now, my PC is damaged and I am using the PC of the company that I work with. 
The problem is that I am having issues to install R studio due to security concerns. 
Is there any other source or method to download R studio ?
Thank you in advance.

**Comment by gmcirco** [comment]
Ilhem,

This is more of an issue with your employer rather than R itself (you might have to ask for specific permissions to install the software).

There are also free versions of R that you can run online via RStudio cloud: https://rstudio.cloud/
