### ISSUE TITLE
Question: Highlighting Cases

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#12]
Having some issues highlighting cases. In the example we are given:

this.shortest <- which.min(Master$height)
this.tallest  <- which.max(Master$height)
this.heaviest <- which.max(Master$weight)

points( Master$height[ this.shortest ], 
        Master$weight[ this.shortest ], 
        col="firebrick", cex=2, lwd=2 #)

I'm struggling with figuring out what variables we are using in our dataset to get the equivalent of "this.shortest, this.tallest, etc". It's using a point on the blue line, so league.ave and league.year, correct? In our dataset what is the equivalent to "master$height" and "which.min"?

**Comment by gmcirco** [comment]
@CarlyDeal 

Correct. It depends on what you are trying to do, but if you want to find the year with the lowest or highest value you would do something like:

`# what is the minimum value in league.ave?`
`league.ave[which.min(league.ave)]`

`# what year did the minimum value occur in?`
`league.year[which.min(league.ave)]`

I should note, you don't need to find the minimum and maximum in the final lab - you just need to annotate two specific points (the league average in 1924 and 2012).
