### ISSUE TITLE
Lab 3: Jitter Issue

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#13]
I've tried several different methods for applying the jitter function and can't seem to figure it out. 

ave.so.jitter comes up as "numeric (empty)

while

year.jitter comes up as "num [1:2955] ...."

Appreciate any help.

**Comment by gmcirco** [comment]
I am not certain where you are trying to use the jitter function. You shouldn't necessarily need it for this lab. However, if you do want to jitter the points, you just need to wrap the function around a numeric vector, like:

`ave.so.jitter <- jitter(ave.so)`

**Comment by JPRayes** [comment]
Thanks for the clarification. I thought Jitter was necessary because the output in R Studio showed something much different than when I knitted the file, giving the plot point the appearance of "mush". Now that I realize the knitted file mirrors the original plots points, I see that jitter is not necessary.
