### ISSUE TITLE
Lab 03: Limiting ave.so data

### ISSUE THREAD

**Issue by ebossert** [Watts-College/cpp-526-spr-2022#14]
Hello,

Can anyone provide some help on how to subset the ave.so data from years 1900 to 2012? I think that it would include creating a new variable of the ave.so for yearID=1900 and 2012, but I cannot figure out how to do it properly and keep encountering errors. I'm thinking that if I can create a subset for each year I can then enter it into plot.window and it will truncate the data to only include the values within 1900-2012. 

Thank you!

**Comment by asukajames** [comment]
I dont think you need to create a new variable! 
```{r}

ave.so <- Teams$SO / Teams$G                      # Calculating average strikeouts per game
year <- Teams$yearID                              # Extracting a vector of years per team

ave.so.min <- min(ave.so, na.rm = TRUE)
ave.so.max <- max(ave.so, na.rm = TRUE)           # Minimum and maximum x-axis limits

league.ave <- tapply(X = ave.so, 
                     INDEX = as.factor(year), 
                     FUN = "mean", 
                     na.rm = TRUE)                # Calculating league strikeout average/season

league.year <- as.numeric(names(league.ave))      # Ensuring years are numeric, not text

```
It's already created and you can find it in the lab template!

**Comment by ebossert** [comment]
Hi @asukajames , thanks for responding! I may have been confusing in my question, but my issue is with the limits of the dataset. Since the Teams data spans from the 1800s to past 2012 it is included in my graph (see below). My question is how to only choose a subset of that data (1900 to 2012) so the x-axis fits the data perfectly. Hopefully that makes sense!

![image](https://user-images.githubusercontent.com/88986971/151561861-900b6421-f932-4da2-8497-4be83bb50a20.png)

**Comment by gmcirco** [comment]
@ebossert 

You will need to apply some sort of filter at the top of your code. For example, you will want to filter the points (in gray) to only fall within 1900 and 2012. You can do something like:

`points(x = year[year %in% 1900:2012], 
       y = ave.so[year %in% 1900:2012],
       col = "gray85",              
       pch = 16,                    
       cex = 0.75)`  

You will need to do this for the averages as well - so keep this in mind.

**Comment by ebossert** [comment]
@gmcirco thank you so much that was very helpful!!
