### ISSUE TITLE
Lab 3: Segments Issue

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#15]
This lab is doing a number on me. I'm running into some series of errors at each step. Not sure if anyone else is experiencing this but it's very draining.

I'm trying to create segments on the plot and continue to receive errors:

segments(
	year = c(1900, 2010),
	ave.so = c(1, 1),
	lty  = “dotted”,
	col = “grey85”
	)

Error: unexpected input in:
"        ave.so = c(1, 1),
        lty  = “"

Not sure if this is a package issue or defining an object issue, but I can't figure out what the error is in all the examples I've seen.

Thanks.

**Comment by sarahysaguirre** [comment]
I approached the segments slightly differently; 

segments(
  x0= 1973,
  y0= 1.8, # starting points of the segments (usually a vector)
  x1= 1973,
  y1= 5.1,  # end points of the segments (usually a vector)
  col = "gray85",   # other arguments from lines()
 )


This worked for all of mine.

**Comment by JPRayes** [comment]
Thank you! I tried that earlier but for some reason wouldn't work either. I pasted your code to see if it would work and it did!
