### ISSUE TITLE
Adding text and getting errors

### ISSUE THREAD

**Issue by kaseympotts** [Watts-College/cpp-526-spr-2022#18]
Current struggle: getting text to show.

I keep getting this warning:
Warning in xy.coords(x, y, recycle = TRUE, setLab = FALSE) :
  NAs introduced by coercion
 
When I use this for the code:

points(x = 1917, y = 1.4, text("U.S. enters WWI"))

What the heck?

**Comment by kaseympotts** [comment]
NEVERMIND!!!! I sorted it out on my own.

I had been combining things that didn't belong!!!

**Comment by JPRayes** [comment]
I separated the points() arguments and the text() arguments. Not sure if that's the most efficient way of doing things.

**Comment by kaseympotts** [comment]
@JPRayes I ended up making every text piece a separate command, too. 

Sometimes most efficient is the way that ends up working.
