### ISSUE TITLE
Lab 4 - could not find function "selectInput" Error

### ISSUE THREAD

**Issue by CynthiaLteif** [Watts-College/cpp-526-spr-2022#20]
I downloaded the Lab 4 template and clicked "run all" and I got an error saying:

Error in selectInput(inputId = "my_team", label = "Select a team:", choices = c("New York Yankees",  : 
  could not find function "selectInput"

I installed the packages needed as mentioned in the instructions 

install.packages( "shiny" )
install.packages( "flexdashboard" )

but the error remains.

I got the same error for the render plot function. 
Error in renderPlot({ : could not find function "renderPlot"

It's as if shiny wasn't installed.

**Comment by gmcirco** [comment]
Hi Cynthia,

I would make sure that both shiny and flexdashboard are loaded into your working environment as well. You should have somewhere in your code the library functions for both:

`library(shiny)`
`library(flexdashboard)`

Check and make sure these are in your code at the top.

**Comment by gmcirco** [comment]
@CynthiaLteif  As a follow-up, any changes you make to your Shiny app will be displayed when you hit "Run Document". You cannot run the code directly in RStudio like in previous lab assignments because the code is reactive and requires an open Shiny app window.

**Comment by CynthiaLteif** [comment]
Thank you, all clear and well noted. @gmcirco
