### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by lilliau** [Watts-College/cpp-526-spr-2022#21]
Hi,

When I run the document, it keeps giving me the message: Error: Trying to use CRAN without setting a mirror. I'm not sure what this means. Will you help with this?
-Lilli

**Comment by ebossert** [comment]
Hi Lilli,

Do you have a install.packages() somewhere in your code? Once I installed everything I deleted those lines and that error went away.

**Comment by lilliau** [comment]
> Hi Lilli,
> 
> Do you have a install.packages() somewhere in your code? Once I installed everything I deleted those lines and that error went away.

Thank you! Yes, I did have that in my code. It worked when I deleted them.
