### ISSUE TITLE
Lab 4 knitting to HTML

### ISSUE THREAD

**Issue by AndrewSchwarz145** [Watts-College/cpp-526-spr-2022#26]
Do we have to knit this lab to a HTML document?  The instructions say to simply run the app to see if it functions.  I made a second markdown document with the YAML header output switched to HTML, which works, but the graph's appearance isn't the same. I also had to use {r echo = FALSE} to make the code disappear so you could see the selection box over the graph, otherwise the code took up too much space requiring the user to scroll down to see their input.

**Comment by gmcirco** [comment]
Andrew,

You just need to submit the lab as a .RMD file. I will be running each file to evaluate them when grading.
