### ISSUE TITLE
Shiny Run Document view vs. Browser view

### ISSUE THREAD

**Issue by lilliau** [Watts-College/cpp-526-spr-2022#29]
I was wondering why my image looks okay when I run the document through shiny, but when I open it in my browser, some of the titles and placements of annotations are messed up. I also noticed that the image adjusts when I maximize the view from my run document. I'm not sure if I need to adjust my code for the maximized shiny view. ???

**Comment by gmcirco** [comment]
This issue is because the size of the plot in Shiny is interactive (as an html object). If you expand or shrink the window the plot will change as well.

This isn't necessarily something to worry about with this lab - the goal is just to get the interactive elements to work.
