### ISSUE TITLE
Lab 2 not clicking

### ISSUE THREAD

**Issue by kaseympotts** [Watts-College/cpp-526-spr-2022#3]
I really need to ask questions when I first get stuck but I am stubborn and therefore have attempted to solve this all day by myself, and am STILL stuck.

Something isn't clicking. 

When combing pieces for the multipart questions like #3 I am missing something. Probably a big something. Probably something obvious to everyone else but I've gotten stuck and can't see past this. 

Code chunk:

# Use variable: 'landuse'
# Use variable: 'yearbuilt'
# Count only commercial properties with buildings constructed during or later than 1980

result <- downtown$landuse == "Commercial"
  sum(downtown$yearbuilt >= 1980, nr.rm = TRUE)

Second two lines are what I did.... and it's definitely NOT right when I run it. 

Am I oversimplifying? Missing a huge step? I think I've fried my brain at this point.

**Comment by ebossert** [comment]
Hi Kasey! I also spent a good amount of time on this, but I think you can combine everything into one step. What I did was:

downtown$landuse == "Commercial" & downtown$yearbuilt >= 1980

Basically once I stopped treating each hashtag as a single step it was easier. Hopefully this helps!

**Comment by kaseympotts** [comment]
@ebossert 
Facepalm.

I think it's time to step away from the computer for a bit. 

Thank you so much!!!
