### ISSUE TITLE
Error running document - Argument 5??

### ISSUE THREAD

**Issue by kaseympotts** [Watts-College/cpp-526-spr-2022#30]
"Argument 5 is empty"

Good grief, I'd love a little red x next to the line(s) so I could troubleshoot this.

Anyone have any help to offer so I know what to fiddle with next?

**Comment by mgintz82** [comment]
I had the same issue and finally found a rouge comma that was unnecessary. Hope you find it!

**Comment by kaseympotts** [comment]
@mgintz82 Thanks for the suggestion. I'll check for extra commas, and parentheses while I'm at it.

**Comment by kaseympotts** [comment]
Found an extra comma and a missing space. Now I get this error:

"Can't access reactive value 'my_team' outside of reactive consumer.
i Do you need to wrap inside reactive() or observe()?"


Current mood (if the image shows):
https://pics.me.me/thumb_it-doesnt-work-why-why-it-works-this-is-so-262889.png

**Comment by mgintz82** [comment]
Unfortunately, that I can't help you with - but your image matches my mood, too!

**Comment by kaseympotts** [comment]
I had a (non-selectable) visible graph for one glorious moment, but I broke it again.
