### ISSUE TITLE
Orange Line Not Appearing

### ISSUE THREAD

**Issue by mgintz82** [Watts-College/cpp-526-spr-2022#31]
I have typed in all of my code and when I run the document the drop down is "working" in that I can select different teams, but nothing changes on the graph itself. What am I missing? It seems like everything is there, but obviously missing a crucial piece.

**Comment by gmcirco** [comment]
One key element you need here is a piece of code to create a line for the team that is selected with the input function. You need to add an additional line that corresponds with the team that was filtered by the reactive function (some of this is annotated in the original lab document).

**Comment by mgintz82** [comment]
After my code from last week I have:

team.name <- input$my_team                 

dat.one.team <- filter(Teams, 
                       name == team.name)   

Teams$ave.so <- Teams$SO / Teams$G
dat.one.team <- filter(Teams, name == "my_team")
points (x=dat.one.team$yearID, y=dat.one.team$ave.so, type="b", pch=19, col="darkorange4")
lines(x=dat.one.team$yearID, y=dat.one.team$ave.so, lwd = 2.5, col = "darkorange4")

But nothing happens. Everything else seems to be showing up correctly.

**Comment by mgintz82** [comment]
Ah ha, I figured it out!

**Comment by AndrewSchwarz145** [comment]
My guess is to remove this line: dat.one.team <- filter(Teams, name == "my_team")
since you already have: dat.one.team <- filter(Teams, name == team.name) 
You want your points to plot with team.name , not "my_team". 

UPDATE: I just wrote this as you posted that you figured it out.  Was this by chance part of your solution?

**Comment by mgintz82** [comment]
It was my line with "dat.one.team <- filter(Teams, name == "my_team"), but I changed it to name == input$my_team and it worked. After reviewing, though, I think you are right since team.name <- input$my_team, so I was duplicating it. It would have gotten me the right answer, thanks!
