### ISSUE TITLE
Lab 5: Time intervals 

### ISSUE THREAD

**Issue by ilhemsaadaoui** [Watts-College/cpp-526-spr-2022#33]
When I run the code to organize time using intervals as it is indicated in the lab, I've got zeros in all time slots exept for 12 AM.

<img width="366" alt="Capture" src="https://user-images.githubusercontent.com/59125432/152699099-0e08b6e4-fccc-46c4-b715-7fb358b238ca.PNG">

 
thank you in advance

**Comment by gmcirco** [comment]
@ilhemsaadaoui 

It's a bit difficult to tell what is happening here based on the code you have. If you run the provided code without any changes, it should generate the table. I would suggest re-running the raw code from the lab.

**Comment by ilhemsaadaoui** [comment]
thank you for your reply. Actually, I run the code as it is in the template.
