### ISSUE TITLE
Issues with Packages

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#34]
When installing the packages I get these errors for a few:

> library( ggmap )    # grab map tiles
Error in library(ggmap) : there is no package called ‘ggmap’
> library( viridis )  # color pallette for maps
Error in library(viridis) : there is no package called ‘viridis’
> library( ggplot2 )  # fancy graphics
> library( ggthemes ) # fancy themes for ggplots
Error in library(ggthemes) : there is no package called ‘ggthemes’

**Comment by gmcirco** [comment]
@CarlyDeal That issue usually refers to a package that has not yet been installed. Be sure to run the following first:

`install.packages("ggmap")`
`install.packages("viridis")`
`install.packages("ggplot2")`
`install.packages("ggthemes")`
