### ISSUE TITLE
Part 3: Plotting Rates of Harm

### ISSUE THREAD

**Issue by ramacdo1** [Watts-College/cpp-526-spr-2022#36]
Good afternoon! I am struggling with the creation of the plots in Part 3 of Week 5's lab. Specifically, I am constantly running into the issue that R Studio is saying that the column 'hour' is not found. I am attaching the following code, although this is one attempt of many to get RStudio to find the column 'hour', and thus likely to have other errors in it. 
``{r}
dat %>% 
  mutate(harm = Totalinjuries + Totalfatalities) %>% 
  select(harm, hour) %>% 
  count(harm) %>% 
  group_by(hour) %>% 
  plot(hour, harm,
       type = 'b')
``
This is the error I get: 
``Error: Must group by variables found in `.data`.
* Column `hour` is not found.
Run `rlang::last_error()` to see where the error occurred.``

I would like to know why RStudio is not recognizing the 'hour' column (I did make sure to run the earlier code chunks creating the hour column, and load all relevant packages). Am I misunderstanding something in the code? Thanks in advance!

**Comment by gmcirco** [comment]
The issue here is that when you do `count(harm)` you are summarizing over just the harm variable. If you want both harm AND hour, you need to do `count(harm,hour)`
