### ISSUE TITLE
Lab 2 Challenge Questions 1 & 2

### ISSUE THREAD

**Issue by droach7** [Watts-College/cpp-526-spr-2022#4]
@gmcirco 

Would it be possible for you to provide a hint/some guidance on challenge questions 1 and 2?

I've briefly tried playing around with a way to calculate assessed value per acre such as:
`result <- (downtown$assessedval / downtown$acres) > 1,000,000`
which yielded too many parcels and did not match the reference map in the instructions.

I thought about trying to create a subset data-frame like we did in question 7 but wasn't sure how to then calculate the price per acre from that.

**Comment by asukajames** [comment]
@droach7 
I think you want to use the downtown$assessedland because it is asking the land value. 
I was able to get the same map as the instruction using the downtown$assessedland   :)

**Comment by droach7** [comment]
It is always the most simple solutions, like making sure I am using the right variable, that evade me after many hours at a computer. Thanks for the help @asukajames! :)
