### ISSUE TITLE
Lab 6: step 4

### ISSUE THREAD

**Issue by CynthiaLteif** [Watts-College/cpp-526-spr-2022#40]
The below code allowed me to find the exact numbers shown in the table of the lab instructions, however, I am unsure how to use the function select() in this case. I still need to include the other variables (lgID, Rank, G) so when I use select(yearID, teamID, lgID, Rank, G) after the arrange() function, I get an error saying:

"`summarise()` has grouped output by 'yearID', 'teamID'. You can override using the `.groups` argument.
 Error: Can't subset columns that don't exist.
x Column `lgID` doesn't exist.
Run `rlang::last_error()` to see where the error occurred."

What am I missing? @gmcirco 

![image](https://user-images.githubusercontent.com/97438499/153722448-90548c7c-3c0a-42f9-a114-37dc9fcc436f.png)

**Comment by gmcirco** [comment]
The issue with your code is that you need to `left_join` your `salaries_teams` dataframe to the `Teams` dataframe. You should note that the variables `lgID` and others are present in the other dataframe - so you need to perform the matching step (show in Step 2 in the lab document) first.

**Comment by CynthiaLteif** [comment]
Thank you for your reply. I did do this step as shown below. The base R method along with the teams1 code were giving me lgID.x and lgID.y which I found odd. So I went with the method shown in the question's example. Did I do something wrong?


![image](https://user-images.githubusercontent.com/97438499/153882788-c9002471-3a92-40e9-a5f2-b00a1c487f05.png)

**Comment by CynthiaLteif** [comment]
Hello @gmcirco I'm still struggling to understand what I've missed. Could you kindly assist?

**Comment by gmcirco** [comment]
Looking at your screenshot it appears the merging worked OK - both your `left_join` functions should work fine.

The .x suffix occurs when you merge and there are two columns named the same thing, but are not being specified by the merge function. I would suggest re-running your code from the top to bottom and not use the base R `merge` function

**Comment by CynthiaLteif** [comment]
Thank you for that. I used the left_join function, ran the code from top to botton, yet my original issue remains [lgID, Rank, and G are missing in final answer and I'm unable to use select due to the above mentioned errors]

I also have to include W in group_by since summarize() is dropping it.

![image](https://user-images.githubusercontent.com/97438499/154327899-0b4519ce-89c1-40bc-b60e-314d540f44c5.png)
