### ISSUE TITLE
Lab 6 Step 3

### ISSUE THREAD

**Issue by asukajames** [Watts-College/cpp-526-spr-2022#42]
Hello! 
I get an error when I try to mutate cost.per.win. 
This is the code I am using: 

Salaries %>%
mutate(cost.per.win = team.budget / (W/100000) )

Error: Problem with `mutate()` column `cost.per.win`. i `cost.per.win = team.budget/(W/100000)`. x object 'team.budget' not found i The error occurred in group 1: yearID = 1985. Run `rlang::last_error()` to see where the error occurred.

I have already used mutate function for team.budget in the Step 1.

**Comment by gmcirco** [comment]
Make sure you are saving the results of your mutate function in each step. If you directly pipe the output (as in your example) this will not save the variable permanently. For example:

`salary_year <- Salaries %>%
  group_by(yearID, teamID) %>%
  summarise(team.budget= sum(salary.adj))`

You can see that I am saving this as a NEW dataframe (you can choose to overwrite the old one, or make a new one). Regardless, you need to be sure you are saving the results of your mutate function somewhere.

**Comment by asukajames** [comment]
Thank you. It worked!
