### ISSUE TITLE
Lab 6: .x and .y

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#43]
I'm confused about the additional columns generated after the two datasets are merged: teamID.x & teamID.y as well as yearID.x and yearID.y. I don't know how to get rid of the unecessary ones and it's messing up the next steps in the process

Comb_Table <- left_join(Salaries, Teams, by="yearID", "teamID")
Comb_Table

**Comment by knewma19** [comment]
I believe you'll need to include "lgID". It is in both datasets

**Comment by JPRayes** [comment]
@knewma19 it worked, thanks!

**Comment by gmcirco** [comment]
Protip: `left_join` will actually automatically merge based on matching column names - you don't even need to specify them by name. The caveat is that it assumes columns with matching names are the ones you want to merge on (not always the case, but in this lab it is).

**Comment by JPRayes** [comment]
@gmcirco  Good to know, thanks!
