### ISSUE TITLE
Lab 6: Step 4 - select() Necessary?

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#45]
I don't seem to need to use the select() function after already using group_by() and summarize():

  group_by(teamID, yearID, lgID, W, L) %>%
   summarize(n = n(), tot_cpw = sum(cost_per_win)) %>%

These two piped functions generate the essential variables. Am I missing something here, or is this just another way to display the required variables?

Also, when I do try to include a select() pipe, I get an error telling me the variables I created do not exist.

**Comment by CynthiaLteif** [comment]
I have the exact same issue.

**Comment by gmcirco** [comment]
This is a matter of what you want to do.

`group_by` 's primary use is to apply a summary function over subsets of the data, then aggregate to those subsets. When you use `group_by` you are telling R to apply a function over the unique groups based on those variables. In some cases it can be OK, but unless you really want to aggregate over all those variables it is best to limit the group_by function to only those variables you want to average over.

Furthermore, in the lab, you use the `Salary` data to create a dataframe of team salaries, then merge this dataframe to the Teams dataframe to get information about wins and losses. So you need to do this separately. Look at the lab document and make sure you are working through the steps in order.

**Comment by ebossert** [comment]
I'm having a same-same-different issue with group_by() where it is seemingly not grouping when I use it even though I'm not getting any errors. I had used it in earlier code chunks without issue, and before merging in Step #3. What am I missing? 
![image](https://user-images.githubusercontent.com/88986971/154394333-3414d401-074b-41ff-9ba0-4c21b6c62d0b.png)

**Comment by gmcirco** [comment]
What is the anticipated output of your code? If you look at what you have, your code says:

"group up the data by yearID and teamID then filter only the teams with 25 or more players"

If you run that, you will get exactly what you asked for. However, what I think you want is to collapse the dataframe into year-team groupings correct? In that case you need to apply a summary function to do this. If you recall from previous labs we typically do this via:

`group_by(groupingVariable) %>% summarize(new_variable = summaryFunction)`

So if you wanted to sum of salaries over year-team groups you might do something like:

`group_by(yearID, teamID) %>% summarize(salary.adj = sum(salary.adj))`

**Comment by ebossert** [comment]
Yep that's exactly what I was aiming for, but I thought group_by() was the function doing the heavy lifting for that result. Thank for you help!
