### ISSUE TITLE
Lab 6: Error when knitting to HTML

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#47]
![knitting error](https://user-images.githubusercontent.com/89749758/154772310-16abc64f-8277-49b5-8733-87ae2f523688.JPG)

I keep getting this error when I try to knit to HTML. Anyone else getting this?

**Comment by mhagan2202** [comment]
Make sure you have ```{r echo = TRUE} at the top of each section. I believe that's what the issue is. If not just remove any pander() functions you have, knit it, and then add them back. That's what I did lol
