### ISSUE TITLE
Code Through Project Due Date?

### ISSUE THREAD

**Issue by mkoenig1-sys** [Watts-College/cpp-526-spr-2022#50]
Hi @gmcirco 

I noticed in the [github course schedule](https://watts-college.github.io/cpp-526-spr-2022/schedule/) that the due date for the Code Through Project is March 11, but in Canvas the due date is March 1, and the ASU Academic Calendar lists the last day of class as March 1. 

**Can you please confirm the correct due date for the Code Through Project?**

Thank you.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/96101119/155220210-169ae07a-1fcd-45b1-b04f-104c6b51e07c.png">

**Comment by gmcirco** [comment]
The due date is, indeed, March 1st (consistent with the Canvas due date and the end-of-class). I'm not certain why it is showing up as March 11 on the other page. I will make a Yellowdig post to clarify.

**Comment by mkoenig1-sys** [comment]
Thank you!
