### ISSUE TITLE
Dashboard Project

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#52]
I  am struggling with my code. I'm trying to show accidents by drivers condition (drug use, alcohol use, and no apparent influence). The code I  have produces the map and the option to choose "Drugs, Alcohol, No influence" on the left, but not data about accidents come up. 

````{r}
` dat.drugs <- dat$DrugUse_Drv1 == "Drugs"

dat.alcohol <- dat$AlcoholUse_Drv1 == "Alcohol"

dat.noD <- dat$DrugUse_Drv1=="No Apparent Influence"
dat.noA <-dat$AlcoholUse_Drv1=="No Apparent Influence"

dat.no <-dat.noD & dat.noA

Under.influence <- dat.drugs & dat.alcohol


radioButtons("under.influence", label = h4("Driver Condition"),
    choices = c("Drugs","Alcohol", "No Apparent influence"), selected = c("Drugs"))

```

Outputs
-------------------------------------

### Condition of Driver

```{r}

# LEAFLET MAPPING

renderLeaflet({


  
  
  d2<-
    dat %>%
    filter(dat.drugs, dat.alcohol, dat.no)
  
  d2$col.vec <- ifelse(d2$dat.drugs, "gray20", ifelse(d2$dat.alcohol, "darkorange", ifelse(d2$dat.no, "steelblue")))           
    
  point.size2 <- d2$dat.drugs + d2$dat.alcohol

  crash.details2 <- paste0("Drug Use: ", d2$dat.drugs, "<br>",
                     "Alcohol Use: ", d2$dat.alcohol, "<br>",
                     "No Apparent Influence:", d2$dat.no)
  
  tempe2 <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe2, lng=d2$Longitude, lat=d2$Latitude,
              fillColor=d2$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size2),
              popup=crash.details2 )


})`

**Comment by ramacdo1** [comment]
I might be wrong, but I think you aren't connecting the user input with the 'behind the scenes' section. You have no inputID that allows the code to make the connection between the User Input and the data you want to use. 

This is from the isolated Dashboard file, but I've chopped it down so it's not a bunch to read:


```{r}

# USER INPUT WIDGETS

    # Allows users to change how data are filtered.
    # Each input widget function has a unique 'inputId ='.
    # The 'inputId' is called with 'input$' in the next code chunk.

    # 'selectInput()' and 'sliderInput()' are examples of widget functions.
    # Each widget has different arguments depending on the type of input used.
    # Find new input widgets here: https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/



selectInput(inputId = "direction1",                 # The unique ID for the input selected
            label = h4("[Dropdown Widget Label]"),
            choices = c("North",                    # The options users can select 
                        "South",                    # These must have corresponding values in the variable
                        "East", 
                        "West"),
            selected = "North")                     # The default input selected


Outputs
-------------------------------------

### [The Title of Your Map]

```{r}

renderLeaflet({
  
  # WHERE UNIQUE IDs ARE USED TO FILTER YOUR DATA
  
      # Function 'filter()' from package 'dplyr' filters data ccording to user inputs.
      # Note that the selected values in each widget above is "called" here with 'input$' and its ID
      # Each input ID must correspond to an existing variable and the input values must also match those of the variable



  d5 <- dat %>%
    filter(Traveldirection_One == input$direction1,   # The unique ID 'direction1' called with 'input$'
           Traveldirection_Two == input$direction2,   # All unique IDs must have a corresponding variable in the data
           hour >= input$hour[1],
           hour <= input$hour[2])                     # Since the slider input has two values, the ID is called twice
```

I think the problem might be in the lack of inputID in your User Interface code, and then it not being called in your filter? That is what worked with mine!

**Comment by CarlyDeal** [comment]
@ramacdo1 Thanks, yeah I'm having issues understanding what I  put for InputID to be able to call it in my filter.

**Comment by CarlyDeal** [comment]
@ramacdo1  Do you have to define inputId before using it in the selectInput() command?

**Comment by ramacdo1** [comment]
@CarlyDeal not in my experience, just identify it for the first time after selectInput!

**Comment by ramacdo1** [comment]
and then in the filter() set the data set variable name == to input$(whatever you called it in selectInput())

**Comment by AndrewSchwarz145** [comment]
@CarlyDeal So for the InputID it usually is a variable, so you don't need to define it, it already should exist.  I am also looking at drug and alcohol use , but instead of using the variables you did (DrugUse_Drv1, AlcoholUse_Drv1), I used d1.substance and d2.substance, which were variables made by the instructors it seems at the top of the code.  They are way easier to use, and their elements are characters instead of factors, which I think makes it easier to use functions on.  They also account for Drug and Alcohol use, instead of just one or the other! So when you make your choice list in the input section of the code, you can make choices for both using that one InputID.  Your choices should correspond to the variable's elements I think.  So for d1.substance, the elements are either "Drugs", "Alcohol", or "No Apparent Influence". Those will be your 3 choices, regardless if you use radioButtons or selectInput, for the widget you make to represent Driver 1.  It will be the same for Driver 2.   

So, I think you should use d1.substance and d2.substance for comparing drivers 1 and drivers 2.  Your InputID will be either one of those variables, make sure to correspond the InputID to the correct driver and widget!   Also, if you use the isolated template (which I also didn't use at first which caused major anxiety....), you will see that the instructors state in the code to not edit the leaflet map instructions at the bottom of the code.  That means you don't need change anything to:

 d5$col.vec <- ifelse(test = d5$nohurt, 
                       yes = "gray20", 
                       no = ifelse(test = d5$inj, 
                                   yes = "steelblue", 
                                   no = "darkorange")) 
  
  point.size <- d5$Totalinjuries + d5$Totalfatalities

  crash.details <- paste0("Time: ", d5$DateTime, "<br>",
                          "Total Fatalities: ", d5$Totalfatalities, "<br>",
                          "Total Injuries: ", d5$Totalinjuries, "<br>",
                          "Collision type: ", d5$Collisionmanner)
  
  tempe <- leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -111.9278, 
            lat = 33.39951, 
            zoom = 13)
  
  
  addCircles(tempe, 
             lng = d5$Longitude, 
             lat = d5$Latitude,
             fillColor = d5$col.vec, 
             fillOpacity = 0.5, 
             stroke = FALSE, 
             radius = 50 * (1 + 0.33 * point.size),
             popup = crash.details)

It should all be the default settings the instructors put in.  The only thing you'd need to change is d5 to whatever you assigned the piped dataset to.  Otherwise your points won't show the nice popup displaying some extra info about the crashes.  The template is also way easier, so use that then copy and paste your code into the final assignment.  Hopefully this comment helps...

**Comment by CarlyDeal** [comment]
@AndrewSchwarz145 do you mind sharing your code? I  tried redoing it and it still does show the info on the map?

`
selectInput(inputId = "druguse",               
            label = h4("[Dropdown Widget Label]"),
            choices = c("Drug Use",
                        "No Apparent Influence"),
            selected = "Drug Use")                   

selectInput(inputId = "alcoholuse", 
            label = h4("[Dropdown Widget Label]"),  
            choices = c("Alcohol Use", 
                        "No Apparent Influence"),
            selected = "Alcohol Use")


  d5 <- dat %>%
    filter(DrugUse_Drv1 == input$druguse,   
           AlcoholUse_Drv1 == input$alcoholuse) `

**Comment by AndrewSchwarz145** [comment]
@CarlyDeal

Here's one of my widgets (I'd share more but idk if that's allowed?)

This is one of my inputs:

selectInput(inputId = "d1.substance",                 # The unique ID for the input selected
                   label = h4("Driver 1:"),
                   choices = c("Alcohol",                     # The options users can select 
                                      "Drugs",                       # These must have corresponding values in the variable
                                      "No Apparent Influence"),
                   selected = "Drugs")                      # The default input selected


the corresponding output: 

d5 <- dat %>%
    filter(d1.substance == input$d1.substance,   # The unique ID 'd1.substance' called with 'input$'
            d2.substance == input$d2.substance)   # All unique IDs must have a corresponding variable in the data

My other input is basically the same, but the correct information is substituted for the variable d2.subtance. 
The template seems really plug and play, as long as you know how the inputId argument works.

**Comment by AndrewSchwarz145** [comment]
@CarlyDeal 

Note that I did not create the variable d1.substance- it was already in the dataset, made for us.  I simply put it in as the inputId, and then made sure the choices corresponded to the variable's levels, which I manually put in.

**Comment by CarlyDeal** [comment]
@AndrewSchwarz145 Thank you! I  was able to get it to work and now see what needs to go where! I really appreciate your help!

**Comment by AndrewSchwarz145** [comment]
@CarlyDeal You're welcome! I am glad I was able to help

**Comment by kaseympotts** [comment]
@CarlyDeal @AndrewSchwarz145 or anyone else still working on this... Can either of you peruse my code and hint at what I've missed?

I'm having a similar issue - everything works (the sidebar options all show up) but crashes aren't populating (I have an empty map).
@gmcirco or anyone, really. I'm grateful for any help, even the smallest re-direction.

Travel Direction on Sunny Days
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

selectInput(inputId = "Traveldirection_One", 
    label = h3("Travel Direction of Driver 1"), 
    choices = list("North", "South", "East", "West"),
    selected = c("East"))

selectInput(inputId = "Traveldirection_Two", 
    label = h3("Travel Direction of Driver 2"), 
    choices = list("North", "South", "East", "West"),
    selected = c("East"))

sliderInput(inputId = "hour", 
            label = h3("Time of Day"), 
            min = 6,
            max = 20, 
            value = c(6, 8))

selectInput(inputId = "Weather", 
    label = h3("Weather conditions"), 
    choices = c("Clear" ),
    selected = c("Clear"))

```

   
Outputs
-------------------------------------

### Travel Direction on Sunny Days


```{r}

#leaflet
renderLeaflet({
  
  drivedirection1 <- input$Traveldirection_One
  drivedirection2 <- input$Traveldirection_Two
  start.time <- input$hour[1]  
  end.time  <-  input$hour[2] 
  
  d4 <- dat %>%
    filter(Traveldirection_One %in% drivedirection1,
           Traveldirection_Two %in% drivedirection2,
          Weather %in% input$Weather,
          hour >= start.time & hour <= end.time )
  
  d4$col.vec <- ifelse( d4$nohurt, "gray20", ifelse(d4$inj, "steelblue", "darkorange") )              
    
  point.size <- d4$Totalinjuries + d4$Totalfatalities

  crash.details <- paste0( "Time: ", d4$DateTime, "<br>",
                     "Total Fatalities: ", d4$Totalfatalities, "<br>",
                     "Total Injuries: ", d4$Totalinjuries, "<br>",
                     "Collision type: ", d4$Collisionmanner)
  
  tempe <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe, lng=d4$Longitude, lat=d4$Latitude,
              fillColor=d4$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size),
              popup=crash.details )


})

**Comment by AndrewSchwarz145** [comment]
@kaseympotts Are you still having a problem? I put your code into the isolated template and the map is populating.

**Comment by kaseympotts** [comment]
@AndrewSchwarz145 
What on earth???  It won't populate when I run the document. I don't know what to do at this point.

**Comment by AndrewSchwarz145** [comment]
@kaseympotts yeah, this is strange... not sure why the map is working for me. let me copy and paste the code in the template: 
(Note that I kept the isolated template's object as d5 in the output section)

[The Title of Your Tab]
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}


selectInput(inputId = "Traveldirection_One", 
    label = h3("Travel Direction of Driver 1"), 
    choices = list("North", "South", "East", "West"),
    selected = c("East"))

selectInput(inputId = "Traveldirection_Two", 
    label = h3("Travel Direction of Driver 2"), 
    choices = list("North", "South", "East", "West"),
    selected = c("East"))

sliderInput(inputId = "hour", 
            label = h3("Time of Day"), 
            min = 6,
            max = 20, 
            value = c(6, 8))

selectInput(inputId = "Weather", 
    label = h3("Weather conditions"), 
    choices = c("Clear" ),
    selected = c("Clear"))



```

Outputs
-------------------------------------

### [The Title of Your Map]

```{r}

renderLeaflet({
  
  drivedirection1 <- input$Traveldirection_One
  drivedirection2 <- input$Traveldirection_Two
  start.time <- input$hour[1]  
  end.time  <-  input$hour[2] 
  
  d5 <- dat %>%
    filter(Traveldirection_One %in% drivedirection1,
           Traveldirection_Two %in% drivedirection2,
          Weather %in% input$Weather,
          hour >= start.time & hour <= end.time )


  # IF CREATING A MAP, YOU CAN IGNORE EVERYTHING BELOW THIS COMMENT
  
  d5$col.vec <- ifelse(test = d5$nohurt, 
                       yes = "gray20", 
                       no = ifelse(test = d5$inj, 
                                   yes = "steelblue", 
                                   no = "darkorange")) 
  
  point.size <- d5$Totalinjuries + d5$Totalfatalities

  crash.details <- paste0("Time: ", d5$DateTime, "<br>",
                          "Total Fatalities: ", d5$Totalfatalities, "<br>",
                          "Total Injuries: ", d5$Totalinjuries, "<br>",
                          "Collision type: ", d5$Collisionmanner)
  
  tempe <- leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -111.9278, 
            lat = 33.39951, 
            zoom = 13)
  
  
  addCircles(tempe, 
             lng = d5$Longitude, 
             lat = d5$Latitude,
             fillColor = d5$col.vec, 
             fillOpacity = 0.5, 
             stroke = FALSE, 
             radius = 50 * (1 + 0.33 * point.size),
             popup = crash.details)

})

```

**Comment by AndrewSchwarz145** [comment]
@kaseympotts I think I found a possible issue.  Did you edit the code below your filter function? I am seeing this difference in our codes:  

Your code:
d4$col.vec <- ifelse( d4$nohurt, "gray20", ifelse(d4$inj, "steelblue", "darkorange") )

The code I posted from the template: 

 d5$col.vec <- ifelse(test = d5$nohurt, 
                       yes = "gray20", 
                       no = ifelse(test = d5$inj, 
                                   yes = "steelblue", 
                                   no = "darkorange"))

maybe using the template's code for d5$col.vec will help.  let me know if it works! I think the arguments are implicit, but sometimes they need to be put in I think.

**Comment by kaseympotts** [comment]
@AndrewSchwarz145 I did not edit it, but I will try what you suggest. Maybe a clumsy click caused something to get weird.

**Comment by kaseympotts** [comment]
@AndrewSchwarz145 I'm still not able to see any crashes populate but thank you very much for trying to help. It's very much appreciated!

I've emailed @gmcirco , and if he, too, sees it populate, I'll have to trust it works without seeing it.

Maybe it's Windows 11 being a jerk to me again.

**Comment by AndrewSchwarz145** [comment]
@kaseympotts I'll keep trying to see why it doesn't work for you but works for me, lol.  Let me know if you find a solution!
