### ISSUE TITLE
Dashboard Project: Checkbox Shiny Widget

### ISSUE THREAD

**Issue by ramacdo1** [Watts-College/cpp-526-spr-2022#53]
I am trying to create a tab that allows for the selection of multiple cases for display on the map. Specifically, I'd like to give users the option to (for example) select Driver 1 to be male, but Driver 2 to be all possible genders (male, female & unknown). When I try to code this using the Shiny Widget, and then run the document, it doesn't appear that all my (selected) data is being displayed. If I click male, and then female for Driver 2, some of the data points for male Driver 2 disappears.  Is it only possible to have one elements data displayed at a time? I have included my code below:

```` {r}
radioButtons(inputId = "GenderPick1",
             label = h4("Gender of Driver 1"),
             choices = c("Male",
                         "Female",
                         "Unknown"),
             selected = "Female")

checkboxGroupInput(inputId = "GenderPick2",
             label = h4("Gender of Driver 2"),
             choices = c("Male",
                         "Female",
                         "Unknown"),
             selected = "Female")

selectInput(inputId = "Driver1Impairment",
                     label = h4("Driver 1 Impairment"), 
                     choices = c("Alcohol",
                                 "Drugs",
                                 "Alcohol and Drugs",
                                 "No Apparent Influence"),
                     selected = "No Apparent Influence")

selectInput(inputId = "Driver2Impairment",
                     label = h4("Driver 2 Impairment"), 
                     choices = c("Alcohol",
                                 "Drugs",
                                 "Alcohol and Drugs",
                                 "No Apparent Influence"),
                     selected = "No Apparent Influence")
````

Outputs
-------------------------------------

### Gender, Impairment & Accidents

```{r}

renderLeaflet({




  d5 <- dat %>%
    filter(Gender_Drv1 == input$GenderPick1,
           Gender_Drv2 == input$GenderPick2,
           d1.substance == input$Driver1Impairment,
           d2.substance == input$Driver2Impairment)                     



  # IF CREATING A MAP, YOU CAN IGNORE EVERYTHING BELOW THIS COMMENT
  
  d5$col.vec <- ifelse(test = d5$nohurt, 
                       yes = "gray20", 
                       no = ifelse(test = d5$inj, 
                                   yes = "steelblue", 
                                   no = "darkorange")) 
  
  point.size <- d5$Totalinjuries + d5$Totalfatalities

  crash.details <- paste0("Time: ", d5$DateTime, "<br>",
                          "Total Fatalities: ", d5$Totalfatalities, "<br>",
                          "Total Injuries: ", d5$Totalinjuries, "<br>",
                          "Collision type: ", d5$Collisionmanner)
  
  tempe <- leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -111.9278, 
            lat = 33.39951, 
            zoom = 13)
  
  
  addCircles(tempe, 
             lng = d5$Longitude, 
             lat = d5$Latitude,
             fillColor = d5$col.vec, 
             fillOpacity = 0.5, 
             stroke = FALSE, 
             radius = 50 * (1 + 0.33 * point.size),
             popup = crash.details)

})

```

**Comment by MonicaCable** [comment]
I was running into a similar issue before, I think you have to include 'gender %in%' in your output. In his example on the first tab he uses the group checkboxes and has them select Friday and Saturday and Sunday, and in the output section you can see that he adds 'day %in%' before setting the filter:

## Input
>checkboxGroupInput("days", 
                   label = h3("Day of Week"), 
    choices = list("Monday"    = "Mon", 
                   "Tuesday"   = "Tue", 
                   "Wednesday" = "Wed", 
                   "Thursday"  = "Thu",
                   "Friday"    = "Fri",
                   "Saturday"  = "Sat",
                   "Sunday"    = "Sun" ),
    selected = c("Fri",
                 "Sat",
                 "Sun"))

>sliderInput(inputId = "hour", 
            label = h3("Time of Day"), 
            min = 0, 
            max = 23, 
            value = c(6, 12))

## Output
>renderLeaflet({
  
 > d2 <- dat %>%
    filter(**day %in%** input$days, 
           hour >= input$hour[1],
           hour <= input$hour[2])

Let me know if that works!

**Comment by ramacdo1** [comment]
@MonicaCable oh this works perfectly! Thank you so much!
