### ISSUE TITLE
Referencing Data set in Dashboard About Section

### ISSUE THREAD

**Issue by AndrewSchwarz145** [Watts-College/cpp-526-spr-2022#54]
I am trying to properly reference the authors/makers of the Tempe dataset we used for the project, but cannot find the page it was originally posted on.  The link provided in the instructions leads to a page that is not found anymore.  Any help in getting the required information would be greatly appreciated. 

Here is the link for reference: https://data.tempe.gov/dataset/high-severity-traffic-crashes-1-08

I also found this page:  https://data.tempe.gov/documents/tempegov::1-08-high-severity-traffic-crashes/about 

which appears to be the most current version of the data set (Both being titled "High Severity Traffic Crashes 1-08." 

this is my current reference: 

Tempe Data. (2019, September 26). 1.08 high severity traffic crashes. Data Catalog. Retrieved February 23, 2022, from https://data.tempe.gov/documents/tempegov::1-08-high-severity-traffic-crashes/about 

It does not include authors since I could not find any.

**Comment by droach7** [comment]
I had the same concern, and ended up with the same reference as you have listed here.

@gmcirco Can you confirm if this is the correct reference you'd like students to use?

Thanks!

**Comment by gmcirco** [comment]
@AndrewSchwarz145 

Yes, as for a reference that is fine. I can also see that the link to the original dataset is gone (alas, one of the issues with relying on open-source datasets). Your reference is A-OK for this project.
