### ISSUE TITLE
Dashboard: Unique vs Levels

### ISSUE THREAD

**Issue by MonicaCable** [Watts-College/cpp-526-spr-2022#56]
In order to set your drop down list you need to type out all of the possible options within a column. I've chosen to use weather conditions and surface conditions for my extra tabs. In order to get a list of all the weather conditions and surface conditions in the data I've used the function unique() like so:

> unique(dat$SurfaceCondition)
[1] Dry                   Unknown               Wet                   Water Standing Moving
Levels: Dry Ice Frost Mud Dirt Gravel Oil Other Unknown Water Standing Moving Wet

I noticed that the Levels include options that aren't in the data such as Ice, Frost, Gravel, etc. Where are these coming from? Am I missing data somehow?

**Comment by ramacdo1** [comment]
I ran into this too, this is a link I found explaining it: https://stackoverflow.com/questions/28645383/understanding-levels-is-levels-not-same-as-unique

Summary is that the levels are all possible values, while unique only uses the values that were actually used in the dataset.

**Comment by gmcirco** [comment]
@ramacdo1 is correct. Factor variables can retain information about all the possible values, but unique will only return those values which are actually present in the data.
