### ISSUE TITLE
Icons in Shiny

### ISSUE THREAD

**Issue by varvel** [Watts-College/cpp-526-spr-2022#57]
I am working on the Final Dashboard project and was hoping to add/update some of the icons used within the value boxes. 

Do these need to be installed somehow, or is there a subset of free icons available within the standard shiny package?

I was trying replace 
`icon = "fa-angry"`
with
`icon = "fa-bandage"`
https://fontawesome.com/icons/bandage?s=solid

For now it just comes out as blank.  Any ideas?

**Comment by anstout** [comment]
In the instructions for the final project, it says:
"You can find new icons for the value boxes in the [Font Awesome Gallery](https://fontawesome.com/icons?d=gallery)."   
I think this is what you're looking for!

**Comment by lilliau** [comment]
Here's a cheat sheet for icons that I found online: https://www1.ucdenver.edu/docs/librariesprovider29/college-of-engineering-and-applied-science/web-resources/cheatsheet-_-font-awesome.pdf

I hope this helps!

**Comment by varvel** [comment]
Thanks you! I was able to use these
