### ISSUE TITLE
Lab 2, Question 4

### ISSUE THREAD

**Issue by MegsBruce** [Watts-College/cpp-526-spr-2022#6]
I feel like this is going to be a very silly question, but I cannot get question #4 to give me anything other than 0 with no map.

![image](https://user-images.githubusercontent.com/88808269/150530556-5966d9fb-ba1e-4452-9c2e-47eec4b93dd5.png)

![image](https://user-images.githubusercontent.com/88808269/150530800-9962a644-0581-4e60-a4fb-57e82ac6b7dc.png)

**Comment by gmcirco** [comment]
I think you might have an extra zero there.  For simplicity, you can also just use scientific notation. 10 million is a 10 with 6 zeroes after it or:

`result <- downtown$assessedval > 10e6`

**Comment by kaseympotts** [comment]
I had the opposite problem last night with one fewer zero and it literally took an hour for me to figure that out. Big empathy here.

**Comment by MegsBruce** [comment]
@gmcirco, thank you! I knew it was going to be something silly like entering the wrong number. I appreciate the quick response.

@kaseympotts, thank you :D My brain says I understand the work, but when I start going the lab things start to blank lol!
