### ISSUE TITLE
Lab 3: Drop-down list and average strikeouts per team

### ISSUE THREAD

**Issue by ilhemsaadaoui** [Watts-College/cpp-526-spr-2022#8]
I have 2 questions:

1/ do we need to plot a scatter plot or a line in the average strikeouts per team ?

2/ to make the drop-down list in the legend, I found that we can use the package "plotly", however, I didn't know how to include it in the code that I have because I must make the graph from scratch with " plotly " then create the legend.

If there is an other solution would please let me know.

**Comment by gmcirco** [comment]
For the plot you will need to mimic the example image as closely as possible. If you look at the picture, you will see that you need to create both a scatterplot (which is the value for each team for each year) and a line chart (which is the average per-year).

You do not need to make a functioning drop down from scratch (although plotly is something that can do this). You just need to manually add a line and text to the top left to mimic the drop down. You can use a combination of `abline()` to do this.

**Comment by CarlyDeal** [comment]
To create the line chart do we use:
line()

Do we have to define average per-year? I'm a little confused on code for creating the blue line.
