### ISSUE TITLE
Week 3: Building Custom Graphics Reading

### ISSUE THREAD

**Issue by CynthiaLteif** [Watts-College/cpp-526-spr-2022#9]
**In 1.4 Highlighting Cases:**
data( Master) 
Master[ which.min(Master$height) , c(14,15,17:20,2) ] %>% pander()

I do not understand what we are trying to do here. What does this combination c(14,15,17:20,2) mean? What does %>% pander() do? 

Not understanding this combination is making it difficult to understand the sections after it. May you kindly assist? @gmcirco

**Comment by gmcirco** [comment]
This is code to produce the example table below the code. There are a few things happening in the following code:

`Master[ which.min(Master$height) , c(14,15,17:20,2) ] %>% pander()`

`Master[ which.min(Master$height)` is finding the individual observation in the data with the smallest height.

`c(14,15,17:20,2) ]` is selecting a subset of columns from the data by location. So this says to take only columns 14,15,17-20, and column 2 at the end. This is done to produce a table with the columns in a custom order.

Finally `%>% pander()` takes the data and adds it to the `pander()` function, which creates an html table. The `%>%` is called a 'pipe' and is used to move data from function to function. You will be working with this a lot more soon.

**Comment by CynthiaLteif** [comment]
Thank makes a lot of sense. Thank you @gmcirco
